/*
 * ControllUnitPanel.java
 *
 * Created on September 23, 2007, 11:29 AM
 */

package ch.eleveneye.hs485.device.physically;

import java.util.Map;

import javax.swing.DefaultListModel;
import javax.swing.SpinnerNumberModel;

import ch.eleveneye.hs485.device.physically.ControllUnit.ControllUnitConfigData;
import ch.eleveneye.hs485.device.physically.ControllUnit.TempRegulatorEntry;

/**
 * 
 * @author akoenig
 */
public class ControllUnitPanel extends javax.swing.JPanel {

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addTempButton;
	private javax.swing.JTextField addTempTextField;
	private javax.swing.JSpinner hystereseSpinner;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSplitPane jSplitPane1;
	private javax.swing.JButton removeTempButton;
	private javax.swing.JButton renameTempButton;
	private javax.swing.JTextField renameTempTextField;
	private javax.swing.JList selectTempList;
	private javax.swing.JSpinner tempSpinner;
	// End of variables declaration//GEN-END:variables
	private final ControllUnitConfigData configData;

	/** Creates new form ControllUnitPanel */
	public ControllUnitPanel(ControllUnitConfigData configData) {
		this.configData = configData;
		initComponents();
		updateTempList();
	}

	private void addTempButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addTempButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_addTempButtonActionPerformed

	private TempRegulatorEntry getCurrentEntry() {
		return configData.getRegulators()
				.get(selectTempList.getSelectedValue());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// <editor-fold defaultstate="collapsed"
	// desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jSplitPane1 = new javax.swing.JSplitPane();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		selectTempList = new javax.swing.JList();
		addTempButton = new javax.swing.JButton();
		removeTempButton = new javax.swing.JButton();
		addTempTextField = new javax.swing.JTextField();
		renameTempButton = new javax.swing.JButton();
		renameTempTextField = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tempSpinner = new javax.swing.JSpinner();
		jLabel2 = new javax.swing.JLabel();
		hystereseSpinner = new javax.swing.JSpinner();

		setLayout(new java.awt.GridBagLayout());

		jSplitPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createLineBorder(getForeground()),
				"Temperatur-Regler"));
		jPanel1.setLayout(new java.awt.GridBagLayout());

		selectTempList
				.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
					public void valueChanged(
							javax.swing.event.ListSelectionEvent evt) {
						selectTempListValueChanged(evt);
					}
				});

		jScrollPane1.setViewportView(selectTempList);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		jPanel1.add(jScrollPane1, gridBagConstraints);

		addTempButton.setText("Hinzuf\u00fcgen");
		addTempButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addTempButtonActionPerformed(evt);
			}
		});

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel1.add(addTempButton, gridBagConstraints);

		removeTempButton.setText("L\u00f6schen");
		removeTempButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				removeTempButtonActionPerformed(evt);
			}
		});

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel1.add(removeTempButton, gridBagConstraints);

		addTempTextField.setText("neuer Regler");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 2.0;
		jPanel1.add(addTempTextField, gridBagConstraints);

		renameTempButton.setText("Umbenennen");
		renameTempButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				renameTempButtonActionPerformed(evt);
			}
		});

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel1.add(renameTempButton, gridBagConstraints);

		renameTempTextField.setText("neuer Name");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 2.0;
		jPanel1.add(renameTempTextField, gridBagConstraints);

		jSplitPane1.setLeftComponent(jPanel1);

		jPanel2.setLayout(new java.awt.GridBagLayout());

		jLabel1.setText("Temperatur");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel2.add(jLabel1, gridBagConstraints);

		tempSpinner.setModel(makeTempSpinner());
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel2.add(tempSpinner, gridBagConstraints);

		jLabel2.setText("Hysterese");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel2.add(jLabel2, gridBagConstraints);

		hystereseSpinner.setModel(makeHystereseSpinner());
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		jPanel2.add(hystereseSpinner, gridBagConstraints);

		jSplitPane1.setRightComponent(jPanel2);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		add(jSplitPane1, gridBagConstraints);

	}// </editor-fold>//GEN-END:initComponents

	public SpinnerNumberModel makeHystereseSpinner() {
		return new SpinnerNumberModel(2, 0.2, 10, 0.2) {
			private static final long serialVersionUID = 3024267760348392330L;

			/*
			 * (non-Javadoc)
			 * 
			 * @see javax.swing.AbstractSpinnerModel#fireStateChanged()
			 */
			@Override
			protected void fireStateChanged() {
				super.fireStateChanged();
				TempRegulatorEntry currentEntry = getCurrentEntry();
				if (currentEntry != null)
					currentEntry.setHysterese(getNumber().doubleValue());
			}
		};
	}

	public SpinnerNumberModel makeTempSpinner() {
		return new SpinnerNumberModel(20, 5, 30, 0.5) {
			private static final long serialVersionUID = 3024267760348392330L;

			/*
			 * (non-Javadoc)
			 * 
			 * @see javax.swing.AbstractSpinnerModel#fireStateChanged()
			 */
			@Override
			protected void fireStateChanged() {
				super.fireStateChanged();
				TempRegulatorEntry currentEntry = getCurrentEntry();
				if (currentEntry != null)
					currentEntry.setTemp(getNumber().doubleValue());
			}
		};
	}

	private void removeTempButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_removeTempButtonActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_removeTempButtonActionPerformed

	private void renameTempButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_renameTempButtonActionPerformed
		// TODO add your handling code here:

	}// GEN-LAST:event_renameTempButtonActionPerformed

	private void selectTempListValueChanged(
			javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_selectTempListValueChanged
		// TODO add your handling code here:
	}// GEN-LAST:event_selectTempListValueChanged

	private void updateCurrentEntry() {
		TempRegulatorEntry currentEntry = getCurrentEntry();
		if (currentEntry != null) {

		}
	}

	private void updateTempList() {
		Object selectedValue = selectTempList.getSelectedValue();
		DefaultListModel defaultListModel = new DefaultListModel();
		Map<String, TempRegulatorEntry> regulators = configData.getRegulators();
		for (String entryName : regulators.keySet()) {
			defaultListModel.addElement(entryName);
		}
		selectTempList.setModel(defaultListModel);
		selectTempList.setSelectedValue(selectedValue, true);
		updateCurrentEntry();
	}
}
